### ISSUE TITLE
Turn off Bluetooth for half an hour

### ISSUE THREAD

**Issue by m4x1mm** [DP-3T/dp3t-sdk-ios#103]
Hi,
I do some test with the sample app, everything was fine i use it with an iPad and an iPhone.
When i turn off the Bluetooth in one of the two device and turn on after 30 minutes, something goes wrong. One of the two devices seems like act only ad receivers the other one Only as sender

**Comment by stmitt** [comment]
We recently undertook a massive refactoring to integrate Apple's official ExposureNotification framework in favour of our custom Bluetooth and Key-generation implementation. Going forward, we will only support the official Apple framework that handles all bluetooth communication. Please update to the latest SDK version and subscribe to the notifications so you keep up to date with the latest changes.
