### ISSUE TITLE
Synchronize with backend

### ISSUE THREAD

**Issue by cpepi001** [DP-3T/dp3t-sdk-ios#112]
Does synchronization with backend happens automatically as Android or we have to force it (Pressing the button)?

I let it more than half an hour and no synchronization happen.
Also the background has status denied.

After one successful force sync, when I try again this error pop ups
```
networkingError The operation couldn't be completed. (DP3TSDK_CALIBRATION.DP3TNetworkingError error 4).
``` 
**_Update 1_**
I had Background App Refresh to off

**_Update 2_**
Wi-Fi is off, pressing sync does not produce any error and updates time

**Comment by stmitt** [comment]
The SDK registers a BackgroundTask which triggers a sync after 2 specific times of the day (~6am and ~6pm). The exact time is unknown as it depends on when iOS launches the app.
Please try with the latest version as we fixed a couple of bugs.
