### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by msireau** [DP-3T/dp3t-sdk-ios#132]
Hello,

Is it possible to have a documentation or a more complete README regarding the current version of dp3t ?

Thank's you

**Comment by UBaggeler** [comment]
We've updated the README and added a document explaining the usage of the EN framework: [EXPOSURE_NOTIFICATION_API_USAGE.md](https://github.com/DP-3T/dp3t-sdk-ios/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md)

For a more complete documentation of the whole system, as deployed by Switzerland (SwissCovid App) please refer to: https://github.com/admin-ch/PT-System-Documents

**Comment by stmitt** [comment]
@msireau: Please consider closing this issue if your question is answered.
