### ISSUE TITLE
BT background proccess

### ISSUE THREAD

**Issue by GrupoGO** [DP-3T/dp3t-sdk-ios#141]
Hi!
With the SDK, would all the processes of BT reading and writing the SDK in the prestandard tag works with app in background? And on iOS <13?

**Comment by UBaggeler** [comment]
Yes, `prestandard` works in the background (relies on GATT service connections) and also supports older versions of iOS. There might be limitations of the BT stack on older devices, which reduce the reliability of GATT connections.
