### ISSUE TITLE
DP3TCryptoModule.checkContacts is not conform to the specification and exposes users to malicious false positives

### ISSUE THREAD

**Issue by LCBH** [DP-3T/dp3t-sdk-ios#17]
The following test
https://github.com/DP-3T/dp3t-sdk-ios/blob/ae498c80250b4ecbfcebf738bd0f04e7b535d6ab/Sources/DP3TSDK/Cryptography/DP3TCryptoModule.swift#L128
does not implement the specification, which mandates to stop computing infected EphIDs one day **before** bucketDate. I would have expected `<` instead of `<=`.

Security implications thereof are pretty bad, see for example a similar bug from issue [reference_implementation/#12](https://github.com/DP-3T/reference_implementation/issues/12). (Essentially, anyone can compute valid, infected EphIDs from some published SK and inject them to the victim the same day as bucketDate.)

**Comment by luc-devallonne-nagra** [comment]
Adding some findings to this issue:

The problem lays wih the fact that when a SecretKey is published to the server, it is then public.
Someone malicious user could then forge EphIDs for that day, impersonating the infectious person during the rest of the day and potentially create a lot of false positives.

To cover this particular case, the [Whitepaper](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf) states (page 11):

_Each smartphone uses this pair to reconstruct the list of EphIDs of an infected
person for each day t’ and checks if it has observed any of these EphIDs **on day t’ in the
past** (i.e., before the corresponding key SKt was published)_

To comply to the above, I beleive the code in:

https://github.com/DP-3T/dp3t-sdk-ios/blob/ae498c80250b4ecbfcebf738bd0f04e7b535d6ab/Sources/DP3TSDK/Cryptography/DP3TCryptoModule.swift#L128

should first compute midnight UTC (start of the day) for the bucketDate and then iterate from the onset Date up to (but not equal) bucketDate midnight UTC

**Comment by Vanuan** [comment]
Looks like a design issue: https://github.com/DP-3T/documents/issues/182

**Comment by luc-devallonne-nagra** [comment]
Actually the implementation is more fine grained than a full day as described in the whitepaper.
Newly released Secret Keys are published on a 2 (configurable?) hours batch window.
This information is carried via the `BucketDate/knownCase.batchTimestamp` when fetched by the device application.

Commit https://github.com/DP-3T/dp3t-sdk-ios/commit/4e18a17746394f6fc4c7eca08ad8938c7973815f#diff-74ac763fc3f0d793c601660e3bcd6041 has added an explicit check  to filter only the contacts seen up to the publication time.

Which should clear the above mentioned threat

**Comment by LCBH** [comment]
Thanks for pointing this commit out. Unfortunately, I don't think the commit solves the issue. Based on the new contacts list considered for a match:

https://github.com/DP-3T/dp3t-sdk-ios/blob/96b0ebc75377df09b1be40a1b9cbeb3c07731764/Sources/DP3TSDK/Cryptography/DP3TCryptoModule.swift#L170

it seems that the same attack works if the "injection" of the forged EphID happens in the same time window as the one corresponding to the batch of the infected SK key (you said "2 (configurable?) hours").

**Comment by luc-devallonne-nagra** [comment]
My observations are the following:
- The device store contacts with a fine grained timestamp
- The server publishes Infectious key on a 2 hours batch basis (aka bucket)
- When a Secret Key is sent to the server, the server makes it available to the world in the next bucket
- The device compare contacts up to the time the SecretKey was made available to the world

So if one forged EphIDs with that newly published Secret Key, and broadcast it around, it should be filtered out by the receiving device

**Comment by Vanuan** [comment]
Let's make some examples.

  * at "2020-05-11 02:00" the server publishes the secret key in the "2020-05-11 00:00" bucket
  * malicious app generates and distributes EphIDs for the "2020-05-11 02:00-04:00" period
  * at "2020-05-11 04:00" all apps will start matching local EphIDs for the "2020-05-11 02:00-04:00" period to EphId generated from the secret keys in the "2020-05-11 00:00" bucket
  * since the condition is `bucketDate >= contact.date`, getDate("2020-05-11 00:00") is equal to getDate("2020-05-11 02:00-04:00"), so the contact alert is shown

**Comment by stmitt** [comment]
A secret key will get published at the end of the bucket period. So if you publish your key at 02:00 the key will appear at 04:00 and not at 00:00.

**Comment by Vanuan** [comment]
@stmitt Does it matter? It appears at the same day. The code only checks the day, not the time.

**Comment by stmitt** [comment]
We recently undertook a massive refactoring to integrate Apple's official ExposureNotification framework in favour of our custom Bluetooth and Key-generation implementation. Going forward, we will only support the official Apple framework that handles all bluetooth communication. Please update to the latest SDK version and subscribe to the notifications so you keep up to date with the latest changes.
