### ISSUE TITLE
iOS < 13.5 support

### ISSUE THREAD

**Issue by mfilippo** [DP-3T/dp3t-sdk-ios#173]
Hello,

Do you plan to support iOS versions prior to 13.5? So the implicit question is: is there any plan to implement DP-3T and therefore be fully compliant with the swiss [Law on Epidemics Art. 60a](https://www.admin.ch/opc/fr/classified-compilation/20071012/index.html#a60a)?

**Comment by UBaggeler** [comment]
The dp3t-sdk-ios currently depends on Apple's [Exposure Notification](https://developer.apple.com/documentation/exposurenotification) framework, which (as of now) is only available for iOS 13.5+.

**Comment by mfilippo** [comment]
Yes, but is there any planning to avoid this dependency in the near future?

**Comment by UBaggeler** [comment]
It is currently not possible on iOS (as opposed to Android) to implement the [Exposure Notification Bluetooth Specification](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-BluetoothSpecificationv1.2.pdf) only using the currently publicly available Bluetooth APIs ([CoreBluetooth](https://developer.apple.com/documentation/corebluetooth)). It is not planned to avoid Apple's Exposure Notification framework.

**Comment by mfilippo** [comment]
Thanks
