### ISSUE TITLE
Background Task and  Sync

### ISSUE THREAD

**Issue by alopezh** [DP-3T/dp3t-sdk-ios#176]
As we can see in the documentation:

"The SDK does not automatically sync with the backend for new exposed users. The app is responsible for fetching the new exposed users as it sees fit (periodically or via user input):"

But it's needed to enable background processiong and setup the following id: "org.dpppt.exposure-notification" in the BGTaskSchedulerPermittedIdentifiers

What is it intended for? 

I want to periodically perfrom the sync with the backend and need this point to be clarified

**Comment by UBaggeler** [comment]
Good point...we will rephrase that. By using the provided EN background processing task, the SDK actually runs syncs even when not triggered by the app.

**Comment by alopezh** [comment]
Thanks, 

Related with this: When does DP3TBackgroundHandler methods are called?

**Comment by UBaggeler** [comment]
The README was updated, see #177. Please consider closing this issue if this answers your question.

**Comment by alopezh** [comment]
One question related to this this issue. When background processing is enabled is it necessary call DP3TTracing.sync explicitly anytme?

**Comment by UBaggeler** [comment]
In case the EN background processing task does not get scheduled (or background refresh is disabled by the user) it is recommended to call sync() when the app is coming to foreground. This makes sure that a sync is performed at least when the app is opened by the user.

**Comment by alopezh** [comment]
Thanks for the info!
