### ISSUE TITLE
No DP3TTracingError.bluetoothTurnedOff error thrown

### ISSUE THREAD

**Issue by alopezh** [DP-3T/dp3t-sdk-ios#181]
Hi 

When the bluetooth is turned off and the  DP3TTracingDelegate is active.  We never receive the state:

TracingState.inactive(error) whith error DP3TTracingError.bluetoothTurnedOff

We always receive TracinState.active even activating and disabling tracing with DP3TTracing.startTracing/stopTracing

Regards

**Comment by UBaggeler** [comment]
Can you elaborate a bit more on the steps to reproduce this issue and which iOS version was used?

**Comment by alopezh** [comment]
The following callback: 
`func DP3TTracingStateChanged(_ state: TracingState)`

never receives `TrackingState.inactive(error: DP3TTracingError)` with the value `DP3TTracingError.bluetoothTurnedOff` if the bluetooth  is turned off. It alwais receive active state

The version is iOS 13.5.1

**Comment by UBaggeler** [comment]
So far we were unable to reproduce your problem. How are you disabling Bluetooth (control center does not disable Bluetooth, you need to disable in the iOS settings). Are you able to provide more logs or even sysdiagnose?

**Comment by alopezh** [comment]
We was disabling it in control center. Is not possible to detect that contition?

**Comment by UBaggeler** [comment]
Tapping the Bluetooth Icon only disconnects from accessories and does not connect to them anymore until the next day. It does not disable Bluetooth.

Apple writes about this: https://support.apple.com/en-us/HT208086

> The icon dims and your device disconnects from any accessory it's connected to, except for Apple Watch, Instant Hotspot, Apple Pencil, and Continuity features, like Handoff.
