### ISSUE TITLE
Rate Limit and Background task

### ISSUE THREAD

**Issue by alopezh** [DP-3T/dp3t-sdk-ios#182]
In the Exposure Notification api usage:
https://github.com/DP-3T/dp3t-sdk-ios/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md

We found this:

> We are only allowed to call detectExposures() 20 times within 24h. Because we check for every of the past 10 days individually, this allows us to check for exposure twice per day. These checks happen after 6am and 6pm (swiss time) when the BackgroundTask is scheduled the next time or the app is opened. All 10 days are checked individually and if one fails it is retried on the next run. No checks are made between midnight UTC and 6am (swiss time) to prevent exceeding the rate limit per 24h.

I can't find in the code where these checks (6am, 6pm) are scheduled. The piece of code I've found:
```
private func scheduleBackgroundTask() {
        logger.trace()
        let taskRequest = BGProcessingTaskRequest(identifier: DP3TBackgroundTaskManager.taskIdentifier)
        taskRequest.requiresNetworkConnectivity = true
        do {
            handler?.didScheduleBackgrounTask()
            try BGTaskScheduler.shared.submit(taskRequest)
        } catch {
            logger.error("background task schedule failed error: %{public}@", error.localizedDescription)
        }
    }
```

Register a BGProcessingTaskRequest wich documentation says:

> Schedule a processing task request to ask that the system launch your app when conditions are favorable for battery life to handle deferrable, longer-running processing, such as syncing, database maintenance, or similar tasks. The system will attempt to fulfill this request to the best of its ability within the next two days as long as the user has used your app within the past week.

Is there any other place in the code where the schedurle restriccions of twice a day are set? Whe are having trouble validating the background checks of the app. It seems it doesn't run in all devices...

**Comment by UBaggeler** [comment]
The background processing task is scheduled at most every 2h but whether `detectExposure()` is actually called is determined in [KnownCasesSynchronizer.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/master/Sources/DP3TSDK/Networking/KnownCasesSynchronizer.swift#L172). `getLastDesiredSyncTime` returns 6am or 6pm. And `daysToCheck` specifies how many days should be checked in the sync call (at the moment 10).

We are also observing issues with the background processing task and are still investigating these issues with Apple (for example after a restart of the device, background processing tasks do not get scheduled until the app is opened again). Let us know what issues you're observing.

**Comment by pantic79** [comment]
Sorry @UBaggeler , but I couldn't figure where the task is scheduled every 2h. Please, could you point me to that in the code?.

**Comment by UBaggeler** [comment]
We're using the provided `exposure-notification` background processing task, which is getting scheduled every 2h. For details please refer to [DP3TBackgroundTaskManager.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/Sources/DP3TSDK/Background/DP3TBackgroundTaskManager.swift).

Apple writes in their documentation:

> The BackgroundTask framework detects apps that contain the Exposure Notification entitlement and a background task that ends in exposure-notification. The operating system automatically launches these apps when they aren’t running and guarantees them more background time to ensure that the app can test and report results promptly.

**Comment by pantic79** [comment]
Thanks @UBaggeler, but I can't see where the 2h delay is specified yet. As far as I understand, no earliestBeginDate is specified and therefore the task should be executed as soon as possible. Right?

BR.

**Comment by UBaggeler** [comment]
This is neither publicly documented by Apple nor easily visible. Normal `BGProcessingTaskRequest` do not get scheduled regularly by iOS (often in the night when phone is being charged and not used). For this special background task, Apple currently configured it to run every 2h. And yes, not specifying `earliestBeginDate` makes it run as soon as possible.

**Comment by pantic79** [comment]
Ok, I see. Thank you so much!

**Comment by stmitt** [comment]
@alopezh: Please consider closing this issue if your question is answered.
