### ISSUE TITLE
Inconsistent comment

### ISSUE THREAD

**Issue by rachyandco** [DP-3T/dp3t-sdk-ios#196]
The following commit https://github.com/DP-3T/dp3t-sdk-ios/commit/54df80ea2576362eb275fdbb118d6dff788d52cc has introduced an inconsistency between a comment and the described function.

The comment of the `setExposed` function on [line 285](https://github.com/DP-3T/dp3t-sdk-ios/blob/54df80ea2576362eb275fdbb118d6dff788d52cc/SampleApp/DP3TSampleApp/ControlViewController.swift#L285) has been modified to refer to the new `numberOfKeysToSubmit` variable instead of the hardcoded value of `14`.

`numberOfKeysToSubmit` has a value of 30 in [DP3TParameters.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/54df80ea2576362eb275fdbb118d6dff788d52cc/Sources/DP3TSDK/DP3TParameters.swift#L36) file.

This means that the following comment 
> `// Share keys of last numberOfKeysToSubmit days`

is understood as
> `// Share keys of last 30 days`

However the `setExposed` function is still using the hardcoded value of `14` in [line 286](https://github.com/DP-3T/dp3t-sdk-ios/blob/54df80ea2576362eb275fdbb118d6dff788d52cc/SampleApp/DP3TSampleApp/ControlViewController.swift#L286)

There is a discrepancy between the comment and the function.

**Comment by pdehaye** [comment]
The situation is further confused by the fact that the variable `numberOfKeysToSubmit` is actually only used in one place, in the [NetworkingHelper.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/SampleApp/DP3TSampleApp/NetworkingHelper.swift#L155-L172) file:

https://github.com/DP-3T/dp3t-sdk-ios/blob/54df80ea2576362eb275fdbb118d6dff788d52cc/SampleApp/DP3TSampleApp/NetworkingHelper.swift#L155-L199

(Note the probably buggy appearance of `14` on line 179 above)

What is the purpose of those changes? The commit message is not very helpful: why jump from 14 to 30 for the debugKeys (are they the same as the fake keys?)?

**Comment by stmitt** [comment]
Thank you for your feedback.

> The comment of the setExposed function on line 285 has been modified to refer to the new numberOfKeysToSubmit variable instead of the hardcoded value of 14.

Yes you are right this is not clear and I reverted the change with PR #197 .

> The situation is further confused by the fact that the variable numberOfKeysToSubmit is actually only used in one place, in the NetworkingHelper.swift file:

The main place where numberOfKeysToSubmit is used inside the SDK is in [DP3TSDK.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/Sources/DP3TSDK/DP3TSDK.swift#L283). It is used to pad the keys submitted to the server to always have the same length so that all POST requests of this kind have the same size.
The increase to 30 is needed since it could be that with future releases of the ENFramework the API might release the current key directly with a rollingPeriod != 144. Therefore there might be multiple keys for one day if multiple apps are calling [getDiagnosisKeys](https://developer.apple.com/documentation/exposurenotification/enmanager/3583725-getdiagnosiskeys) for the same day.

Does this clarify the change?

**Comment by pdehaye** [comment]
It certainly clarifies the intent of the change. Thank you for pointing out how/where `numberOfKeysToSubmit` is actually used (GitHub search failed me by only showing top match).

Something still bugs me. Let's say you have a user who has ever installed only SwissCovid (so no problems with multiple apps), and who wants to upload their codes. Then [`iWasExposed` will call `getDiagnosisKeys`](https://github.com/DP-3T/dp3t-sdk-ios/blob/54df80ea2576362eb275fdbb118d6dff788d52cc/Sources/DP3TSDK/DP3TSDK.swift#L268), which in turn will call [`getDiagnosisKeysInternal`](https://github.com/DP-3T/dp3t-sdk-ios/blob/4ab9c2044e47a632fdbf4f48c7d4a7b3cd9345a0/Sources/DP3TSDK/Cryptography/DiagnosisKeysProvider.swift#L63). The latter function builds an API-internal [`ENGetDiagnosisKeysHandler`](https://developer.apple.com/documentation/exposurenotification/engetdiagnosiskeyshandler), which in turn will deliver some number X of keys. This number will then be filtered by [this line](https://github.com/DP-3T/dp3t-sdk-ios/blob/4ab9c2044e47a632fdbf4f48c7d4a7b3cd9345a0/Sources/DP3TSDK/Cryptography/DiagnosisKeysProvider.swift#L81) according to onset date and by [this line](https://github.com/DP-3T/dp3t-sdk-ios/blob/4ab9c2044e47a632fdbf4f48c7d4a7b3cd9345a0/Sources/DP3TSDK/Cryptography/DiagnosisKeysProvider.swift#L91) down to `numberOfKeysToSubmit`. What is X? Are there safeguards in place to prevent a doctor from entering an onset date way in the past and get `min(X, numberOfKeysToSubmit)` uploaded?

**Comment by stmitt** [comment]
@pdehaye iOS internally deletes data after 14 Days. But you are right, I added a parameter `maxAgeOfKeyToRetreive` which is filters the keys retrieved from the ENFramework before we do the filtering for the onset date. 
This is addressed in PR #197 does this resolve your concerns?

**Comment by pdehaye** [comment]
> iOS internally deletes data after 14 Days

I agree this would be a Swiss legal requirement of the system, but where is the source for that assertion on the behavior of iOS? the [doc for v1 of the framework](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/calculating_the_exposure_risk_value_in_exposurenotification_version_1) includes as part of the calculation a "Days Risk Parameter" applicable for days >= 14. Version 1.5 is harder for me to understand at the moment.

#197 seems fine in the intent, I am unable to assess the correctness of the code.

**Comment by stmitt** [comment]
The [crypto specification](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf?1) of apple states that the device stores 14 keys (1 key/day).

@rachyandco:  Please consider closing this issue if your question is answered.

**Comment by pdehaye** [comment]
@stmitt That statement in the crypto spec refers only to the device storing their "own" TEKs for 14 days only, which is indeed what is relevant for this issue. _But_ the crypto specification does _not_ say that "iOS internally deletes data after 14 Days" (a statement for which I have seen no source as far as "heard" RPIs are concerned).

**Comment by stmitt** [comment]
@pdehaye  iOS and Android states in their settings app that recorded IDs are only stored 14 days.
![iOS](https://user-images.githubusercontent.com/1466567/89630903-4f002d00-d8a0-11ea-94d5-3278d49d11a9.png)
![android](https://user-images.githubusercontent.com/1466567/89630911-51fb1d80-d8a0-11ea-98ae-28ba884d7832.png)

**Comment by pdehaye** [comment]
Thanks, yes. That seems to cover it. My iPhone is too old for the Exposure Notification system, and I don't have an Android one at hand.
