### ISSUE TITLE
Missing changes in version 1.1.0

### ISSUE THREAD

**Issue by henrimagi** [DP-3T/dp3t-sdk-ios#199]
While the commit history includes MR #188, the changes of that commit were not merged to master with #192. You can check by doing `git diff 4ab9c2044e47a632fdbf4f48c7d4a7b3cd9345a0..master`. This probably has something to do with the mishap that the first MR was merged to master and reverted. Finally a new MR was made to target develop.

Could we do a version 1.1.1 that will include the changes?

**Comment by stmitt** [comment]
these changes are now in release 1.1.1
