### ISSUE TITLE
Simplify hashing

### ISSUE THREAD

**Issue by ineiti** [DP-3T/dp3t-sdk-ios#2]
First time SWIFTer here, so caution.

In https://github.com/DP-3T/dp3t-sdk-ios/blob/develop/Sources/DP3TSDK/Cryptography/Crypto.swift#L11, the connection with the `CommonCrypto` library looks somewhat convoluted. For once I prefer the stackoverflow answer here: https://stackoverflow.com/a/25391020/1573347

**Comment by stmitt** [comment]
resolved with https://github.com/DP-3T/dp3t-sdk-ios/pull/8
