### ISSUE TITLE
iOS 13.7: rate-limit set to 15 calls per 24h

### ISSUE THREAD

**Issue by stmitt** [DP-3T/dp3t-sdk-ios#211]
Apple unfortunately decreased the rate-limit of calling EN.detectExposured in iOS 13.7 to 15 calls per 24h instead of the 20 calls (2x a full sync per day) we were allowed to make on previous iOS versions. 
With this limitation, the app is only to check against 15 days/day instead of 20 days/day.

We are in contact with Apple about this.

**Comment by r-r-liu** [comment]
Seems back to the two successful syncs per day, 9 days each successful sync.

**Comment by fmaia** [comment]
Yes, I'm observing a 20-check limit again with iPhone XS, iOS 13.7, STAYAWAY COVID (the Portuguese app). 
3 days ago I was observing the 15-check limit.

**Comment by stmitt** [comment]
The configuration was changed back to 20 Checks per 24h. This resolves this issue.

**Comment by stmitt** [comment]
As this resurfaced (https://github.com/DP-3T/dp3t-app-ios-ch/issues/249) for the SwissCovid app I reopen this issue. 
It seems that the configuration was set back to 15 calls/day for some users.

**Comment by UBaggeler** [comment]
Starting with dp3t-sdk-ios v2 the SDK uses the new ENv2 API, which does not have this limitation anymore.
