### ISSUE TITLE
Tipos in doc

### ISSUE THREAD

**Issue by pelinquin** [DP-3T/dp3t-sdk-ios#31]
It is not clear weather when one should include DP3TSDK and when use ST3PSDK_CALIBRATION

Also the given initialization function 
 DP3TTracing.initialize
has a ) missing

Please give one or two exemples that compile
Thankyou

**Comment by VittoriDavide** [comment]
I think we have to include just the DP3TSDK package since the calibration is an app to test

**Comment by stmitt** [comment]
The DP3PSDK_CALIBRATION package is includes logging functionality and should not be used in production. The missing bracket is fixed now.
