### ISSUE TITLE
services for reporting and downloading keys (/v1/exposed) possibly swapped?

### ISSUE THREAD

**Issue by govcert-ch** [DP-3T/dp3t-sdk-ios#53]
I originally left this issue in the CH app git, but I think it's an issue in the backend code (if it's an issue), hence I repeat it here so it's not missed (sorry for the initially wrong posting)

In `DP3TSDK/Networking/ExposeeServiceClient.swift`:
```
/// The endpoint for getting exposee
private let exposeeEndpoint: ExposeeEndpoint
/// The endpoint for adding and removing exposee
private let managingExposeeEndpoint: ManagingExposeeEndpoint
```
so I guess `exposeeEndpoint` is used to download keys (`GET /v1/exposed/`), and `managingExposeeEndpoint` would be used to report keys (`POST /v1/exposed/`). In many cases, these would end at the same endpoint, but they can also differ (DDOS protection etc). This assumption I think is supported by the later code:
```
/// Adds an exposee
/// - Parameters:
///   - exposee: The exposee to add
///   - completion: The completion block
///   - authentication: The authentication to use for the request
func addExposee(_ exposee: ExposeeModel, authentication: ExposeeAuthMethod, completion: @escaping (Result<Void, DP3TTracingError>) -> Void) {

    // addExposee endpoint
    let url = managingExposeeEndpoint.addExposee()

    guard let payload = try? JSONEncoder().encode(exposee) else {
        completion(.failure(.networkingError(error: nil)))
        return
    }

    var request = URLRequest(url: url)
    request.httpMethod = "POST"
```
which clearly is a POST to `managingExposeeEndpoint`and so should go to the report URL. The other code is
```
/// Get all exposee for a known day synchronously
/// - Parameters:
///   - batchTimestamp: The batch timestamp
///   - completion: The completion block
/// - returns: array of objects or nil if they were already cached
func getExposeeSynchronously(batchTimestamp: Date) -> Result<[KnownCaseModel]?, DP3TTracingError> {
    let url = exposeeEndpoint.getExposee(batchTimestamp: batchTimestamp)
    var request = URLRequest(url: url, cachePolicy: .useProtocolCachePolicy, timeoutInterval: 60.0)
    request.setValue("application/x-protobuf", forHTTPHeaderField: "Accept")
```
which is the GET request (using `application/x-protobuf` as binary download format).

However, in the actual assignments, we see:
```
exposeeEndpoint = ExposeeEndpoint(baseURL: descriptor.reportBaseUrl)
managingExposeeEndpoint = ManagingExposeeEndpoint(baseURL: descriptor.bucketBaseUrl)
```
And that looks as if the 2 assignments are swapped, shouldn't `managingExposeeEndpoint` go to the`descriptor.reportBaseUrl` and vice versa?

**Comment by stmitt** [comment]
Yes, you're right. I’ll correct the mistake. Thanks for pointing it out.
