### ISSUE TITLE
Deploy/push new .podspec

### ISSUE THREAD

**Issue by bantunes22** [DP-3T/dp3t-sdk-ios#57]
Hi, can you please deploy/push the new .podspec to cocoapods to include the ProtoBuf and SwiftJWT dependency please?

Thanks

**Comment by stmitt** [comment]
Hi, 
i pushed it right now, can you check if it's working for you?
Thanks

**Comment by bantunes22** [comment]
@stmitt working properly now thanks!

Used `pod 'DP3TSDK', '0.0.2'`. Maybe update the documentation 😊 

Thanks!
