### ISSUE TITLE
Type 'DP3TTracing' has no member 'performFetch'

### ISSUE THREAD

**Issue by alexnivanov** [DP-3T/dp3t-sdk-ios#64]
The README says:
_To support background fetch on devices with older iOS versions make sure to foreward the performFetchWithCompletionHandler call to the SDK._

```
func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {  
    DP3TTracing.performFetch(with: completionHandler)
}
```

However, Xcode says that `Type 'DP3TTracing' has no member 'performFetch'`

**Comment by joseph-elmallah** [comment]
This is no longer the case, thank you for pointing it out. We will remove it from the documentation. As of now, we rely on the Background Tasks provided by Apple's **BGTaskScheduler** https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler.
