### ISSUE TITLE
Repeated batchReleaseTime

### ISSUE THREAD

**Issue by tillmzw** [DP-3T/dp3t-sdk-ios#88]
Dear all,

First of all - I'm not versed in Swift, so I may misunderstand code, but here it goes:
In the API consuming part in [ExposeeServiceClient.swift](https://github.com/DP-3T/dp3t-sdk-ios/blob/master-alpha/Sources/DP3TSDK/Networking/ExposeeServiceClient.swift) you are raising an error if the `batchReleaseTime` of the response does not match that of the request [here](https://github.com/DP-3T/dp3t-sdk-ios/blob/master-alpha/Sources/DP3TSDK/Networking/ExposeeServiceClient.swift#L80). Isn't this redundant and shouldn't the backend have the last word so to say about the batch release time?

I may also be a bit confused about the meaning of the release time - per my understanding it is the last completed/concluded time block (defaulting to 2h) up until now. So if the server has 2h release time blocks, and I request a block of keys at say 15:15, shouldn't I get all keys that were released between 12:00 and 14:00?

**Comment by stmitt** [comment]
We recently undertook a massive refactoring to integrate Apple's official ExposureNotification framework in favour of our custom Bluetooth and Key-generation implementation. Going forward, we will only support the official Apple framework that handles all bluetooth communication. Please update to the latest SDK version and subscribe to the notifications so you keep up to date with the latest changes.
