### ISSUE TITLE
Need a Handshake callback in the API, not a DB request

### ISSUE THREAD

**Issue by pelinquin** [DP-3T/dp3t-sdk-ios#93]
Hello,
I tried to make a simple "HelloWorld Contact Tracing" Swift file for iOs
https://github.com/pelinquin/kissact/blob/master/hello_DP3T.swift

But I had to add a button to get the last Handshake.
I seems that the SQL database is mandatory with the SDK.
I would have prefer to have to register a callback function, for each received message.
I may want to use my own persistant system

**Comment by pelinquin** [comment]
I'am sorry, I found the way to fix it

**Comment by msireau** [comment]
Hello, 
I wonder how you are able to import DP3TSDK_CALIBRATION ?
Do you use cocoapods ?
Thx 🙏
