### ISSUE TITLE
How to set my own EphIds with the SDK ?

### ISSUE THREAD

**Issue by pelinquin** [DP-3T/dp3t-sdk-ios#94]
![A25AF17A-6199-468C-95BF-EC2196A319C1](https://user-images.githubusercontent.com/220488/82140660-ac9c5480-9830-11ea-9c4f-2ec1fcfa2ad0.png)
![50B34B93-9AE2-4E12-9E26-F698DF1BE664_4_5005_c](https://user-images.githubusercontent.com/220488/82140667-b756e980-9830-11ea-8b0f-09c7411376a4.jpeg)

I want to build an app with the SDK but I need to set the sent Ephids  of my own

Does the SDK allows that ?
What service to call ?

Thanks

**Comment by stmitt** [comment]
Hi, what do you mean by setting your own EphIDs?

**Comment by stmitt** [comment]
We recently undertook a massive refactoring to integrate Apple's official ExposureNotification framework in favour of our custom Bluetooth and Key-generation implementation. Going forward, we will only support the official Apple framework that handles all bluetooth communication. Please update to the latest SDK version and subscribe to the notifications so you keep up to date with the latest changes.
